name: Python Jobs

on: [push, pull_request]

jobs:
  job_1:
    name: Base (geopandas+pandas+openpyxl)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl -c conda-forge
      - shell: pwsh
        run: python kernel_test.py

  job_2:
    name: +numpy
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl numpy>=2 -c conda-forge
      - shell: pwsh
        run: python kernel_test.py

  job_3:
    name: +numba
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl numpy>=2 numba -c conda-forge
      - shell: pwsh
        run: python kernel_test.py

  job_4:
    name: +matplotlib
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl numpy>=2 numba matplotlib -c conda-forge
      - shell: pwsh
        run: python kernel_test.py

  job_5:
    name: +fiona
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl numpy>=2 numba matplotlib fiona -c conda-forge
      - shell: pwsh
        run: python kernel_test.py

  job_6:
    name: +gdal
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl numpy>=2 numba matplotlib fiona gdal>=3.7 -c conda-forge
      - shell: pwsh
        run: python kernel_test.py

  job_7:
    name: +rasterio
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl numpy>=2 numba matplotlib fiona gdal>=3.7 rasterio -c conda-forge
      - shell: pwsh
        run: python kernel_test.py

  job_8:
    name: +osmnx
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl numpy>=2 numba matplotlib fiona gdal>=3.7 rasterio osmnx>=1.9.4 -c conda-forge
      - shell: pwsh
        run: python kernel_test.py

  job_9:
    name: +momepy
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl numpy>=2 numba matplotlib fiona gdal>=3.7 rasterio osmnx>=1.9.4 momepy -c conda-forge
      - shell: pwsh
        run: python kernel_test.py

  job_10:
    name: +tobler
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl numpy>=2 numba matplotlib fiona gdal>=3.7 rasterio osmnx>=1.9.4 momepy tobler -c conda-forge
      - shell: pwsh
        run: python kernel_test.py

  job_11:
    name: +h3-py
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl numpy>=2 numba matplotlib fiona gdal>=3.7 rasterio osmnx>=1.9.4 momepy tobler h3-py -c conda-forge
      - shell: pwsh
        run: python kernel_test.py

  job_12:
    name: +contextily
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl numpy>=2 numba matplotlib fiona gdal>=3.7 rasterio osmnx>=1.9.4 momepy tobler h3-py contextily -c conda-forge
      - shell: pwsh
        run: python kernel_test.py

  job_13:
    name: +libpysal
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl numpy>=2 numba matplotlib fiona gdal>=3.7 rasterio osmnx>=1.9.4 momepy tobler h3-py contextily libpysal -c conda-forge
      - shell: pwsh
        run: python kernel_test.py

  job_14:
    name: +shapely>=2
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl numpy>=2 numba matplotlib fiona gdal>=3.7 rasterio osmnx>=1.9.4 momepy tobler h3-py contextily libpysal shapely>=2.0 -c conda-forge
      - shell: pwsh
        run: python kernel_test.py

  job_15:
    name: +xlsxwriter
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl numpy>=2 numba matplotlib fiona gdal>=3.7 rasterio osmnx>=1.9.4 momepy tobler h3-py contextily libpysal shapely>=2.0 xlsxwriter -c conda-forge
      - shell: pwsh
        run: python kernel_test.py

  job_16:
    name: +fuzzywuzzy
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl numpy>=2 numba matplotlib fiona gdal>=3.7 rasterio osmnx>=1.9.4 momepy tobler h3-py contextily libpysal shapely>=2.0 xlsxwriter fuzzywuzzy -c conda-forge
      - shell: pwsh
        run: python kernel_test.py

  job_17:
    name: +owslib
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl numpy>=2 numba matplotlib fiona gdal>=3.7 rasterio osmnx>=1.9.4 momepy tobler h3-py contextily libpysal shapely>=2.0 xlsxwriter fuzzywuzzy owslib -c conda-forge
      - shell: pwsh
        run: python kernel_test.py

  job_18:
    name: +joblib
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl numpy>=2 numba matplotlib fiona gdal>=3.7 rasterio osmnx>=1.9.4 momepy tobler h3-py contextily libpysal shapely>=2.0 xlsxwriter fuzzywuzzy owslib joblib -c conda-forge
      - shell: pwsh
        run: python kernel_test.py

  job_19:
    name: +pyutilib
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl numpy>=2 numba matplotlib fiona gdal>=3.7 rasterio osmnx>=1.9.4 momepy tobler h3-py contextily libpysal shapely>=2.0 xlsxwriter fuzzywuzzy owslib joblib pyutilib -c conda-forge
      - shell: pwsh
        run: python kernel_test.py

  job_20:
    name: +pyomo
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl numpy>=2 numba matplotlib fiona gdal>=3.7 rasterio osmnx>=1.9.4 momepy tobler h3-py contextily libpysal shapely>=2.0 xlsxwriter fuzzywuzzy owslib joblib pyutilib pyomo>=6.8 -c conda-forge
      - shell: pwsh
        run: python kernel_test.py

  job_21:
    name: +addict
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl numpy>=2 numba matplotlib fiona gdal>=3.7 rasterio osmnx>=1.9.4 momepy tobler h3-py contextily libpysal shapely>=2.0 xlsxwriter fuzzywuzzy owslib joblib pyutilib pyomo>=6.8 addict -c conda-forge
      - shell: pwsh
        run: python kernel_test.py

  job_22:
    name: +blinker
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl numpy>=2 numba matplotlib fiona gdal>=3.7 rasterio osmnx>=1.9.4 momepy tobler h3-py contextily libpysal shapely>=2.0 xlsxwriter fuzzywuzzy owslib joblib pyutilib pyomo>=6.8 addict blinker -c conda-forge
      - shell: pwsh
        run: python kernel_test.py

  job_23:
    name: +dill
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl numpy>=2 numba matplotlib fiona gdal>=3.7 rasterio osmnx>=1.9.4 momepy tobler h3-py contextily libpysal shapely>=2.0 xlsxwriter fuzzywuzzy owslib joblib pyutilib pyomo>=6.8 addict blinker dill -c conda-forge
      - shell: pwsh
        run: python kernel_test.py

  job_24:
    name: +nose
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl numpy>=2 numba matplotlib fiona gdal>=3.7 rasterio osmnx>=1.9.4 momepy tobler h3-py contextily libpysal shapely>=2.0 xlsxwriter fuzzywuzzy owslib joblib pyutilib pyomo>=6.8 addict blinker dill nose -c conda-forge
      - shell: pwsh
        run: python kernel_test.py

  job_25:
    name: +deepdiff
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl numpy>=2 numba matplotlib fiona gdal>=3.7 rasterio osmnx>=1.9.4 momepy tobler h3-py contextily libpysal shapely>=2.0 xlsxwriter fuzzywuzzy owslib joblib pyutilib pyomo>=6.8 addict blinker dill nose deepdiff -c conda-forge
      - shell: pwsh
        run: python kernel_test.py

  job_26:
    name: +geojson
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl numpy>=2 numba matplotlib fiona gdal>=3.7 rasterio osmnx>=1.9.4 momepy tobler h3-py contextily libpysal shapely>=2.0 xlsxwriter fuzzywuzzy owslib joblib pyutilib pyomo>=6.8 addict blinker dill nose deepdiff geojson -c conda-forge
      - shell: pwsh
        run: python kernel_test.py

  job_full:
    name: Full Environment File
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
          environment-file: environment_full.yaml
      - shell: pwsh
        run: python kernel_test.py
