name: Python Jobs

on: [push, pull_request]

jobs:
  job_1:
    name: Base (geopandas+pandas+openpyxl)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl -c conda-forge
      - name: Show environment info
        shell: pwsh
        run: |
          conda info
          conda list
      - name: Dump environment details
        shell: pwsh
        run: |
          conda info > conda_info.txt
          conda list > conda_list.txt

      - name: Upload environment artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "${{ github.job }}-py${{ matrix.python-version }}-${{ matrix.os }}"
          path: |
            conda_info.txt
            conda_list.txt
      - shell: pwsh
        run: python kernel_test.py

  job_2:
    name: Full Environment File (defaults, conda-forge)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          channels: defaults,conda-forge
          python-version: ${{ matrix.python-version }}
          environment-file: environment_full.yaml
      - name: Show environment info
        shell: pwsh
        run: |
          conda info
          conda list
      - name: Dump environment details
        shell: pwsh
        run: |
          conda info > conda_info.txt
          conda list > conda_list.txt

      - name: Upload environment artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "${{ github.job }}-py${{ matrix.python-version }}-${{ matrix.os }}"
          path: |
            conda_info.txt
            conda_list.txt
      - shell: pwsh
        run: python kernel_test.py

  job_3:
    name: Full Environment File (conda-forge only)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          channels: conda-forge
          python-version: ${{ matrix.python-version }}
          environment-file: environment_full_no_defaults.yaml
      - name: Show environment info
        shell: pwsh
        run: |
          conda info
          conda list
      - name: Dump environment details
        shell: pwsh
        run: |
          conda info > conda_info.txt
          conda list > conda_list.txt

      - name: Upload environment artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "${{ github.job }}-py${{ matrix.python-version }}-${{ matrix.os }}"
          path: |
            conda_info.txt
            conda_list.txt
      - shell: pwsh
        run: python kernel_test.py

  job_4:
    name: defaults, conda-forge
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ['3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          channels: defaults,conda-forge
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl scipy numpy>=2 numba matplotlib osmnx>=1.9.4 momepy coolprop fiona gdal>=3.7 rasterio tobler h3-py contextily libpysal shapely>=2.0 xlsxwriter fuzzywuzzy owslib joblib pyutilib pyomo>=6.8 addict blinker dill nose deepdiff geojson -c defaults -c conda-forge
      - name: Show environment info
        shell: pwsh
        run: |
          conda info
          conda list
      - name: Dump environment details
        shell: pwsh
        run: |
          conda info > conda_info.txt
          conda list > conda_list.txt

      - name: Upload environment artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "${{ github.job }}-py${{ matrix.python-version }}-${{ matrix.os }}"
          path: |
            conda_info.txt
            conda_list.txt
      - shell: pwsh
        run: python kernel_test.py

  job_5:
    name: conda-forge only
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ['3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          channels: conda-forge
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl scipy numpy>=2 numba matplotlib osmnx>=1.9.4 momepy coolprop fiona gdal>=3.7 rasterio tobler h3-py contextily libpysal shapely>=2.0 xlsxwriter fuzzywuzzy owslib joblib pyutilib pyomo>=6.8 addict blinker dill nose deepdiff geojson -c conda-forge
      - name: Show environment info
        shell: pwsh
        run: |
          conda info
          conda list
      - name: Dump environment details
        shell: pwsh
        run: |
          conda info > conda_info.txt
          conda list > conda_list.txt

      - name: Upload environment artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "${{ github.job }}-py${{ matrix.python-version }}-${{ matrix.os }}"
          path: |
            conda_info.txt
            conda_list.txt
      - shell: pwsh
        run: python kernel_test.py

  job_6:
    name: pip only
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip dependencies
        run: |
          pip install --upgrade pip
          pip install geopandas pandas openpyxl scipy numpy>=2 numba matplotlib osmnx>=1.9.4 momepy coolprop fiona gdal>=3.7 rasterio tobler h3 contextily libpysal shapely>=2.0 xlsxwriter fuzzywuzzy owslib joblib pyutilib pyomo>=6.8 addict blinker dill nose deepdiff geojson

      - name: Dump installed packages
        run: pip freeze > installed_packages_pip.txt

      - uses: actions/upload-artifact@v4
        with:
          name: "${{ github.job}} - py${{ matrix.python-version }} - ${{ matrix.os }}"
          path: installed_packages_pip.txt

      - name: Run kernel test
        run: python kernel_test.py
