name: Python Jobs

on: [push, pull_request]

jobs:
  job_1:
    name: Base (geopandas+pandas+openpyxl)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
      - shell: pwsh
        run: conda install geopandas pandas openpyxl -c conda-forge
      - shell: pwsh
        run: python kernel_test.py

  job_full:
    name: Full Environment File (defaults, conda-forge)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
          environment-file: environment_full.yaml
      - shell: pwsh
        run: python kernel_test.py

  job_full_no_defaults:
    name: Full Environment File (conda-forge only)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ["3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: work
          python-version: ${{ matrix.python-version }}
          environment-file: environment_full_no_defaults.yaml
      - shell: pwsh
        run: python kernel_test.py
